### ISSUE TITLE
Clicking the force upload in the Android applications causes error on the server

### ISSUE THREAD

**Issue by keesj** [PhotoBackup/server-bottle#12]
After a failed upload (due to wrong size...I don't know what happend)
xxx.xxx.xxx.112 - - [13/Dec/2015 21:15:37] "POST / HTTP/1.1" 411 755

I pressed the logwindow and forced the upload:
xxx.xxx.xxx.112 - - [13/Dec/2015 21:49:27] "POST /test HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(*_args)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(_a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/photobackup_bottle/photobackup.py", line 130, in save_image
    upfile.save(path)
  File "/usr/local/bin/bottle.py", line 2392, in save
    raise IOError('File exists.')
IOError: File exists.

**Comment by stephanepechard** [comment]
I have to check on this, but I suspect it is because you use Python 2.7, and PhotoBackup only support Python 3...
